# Generated by Django 5.0.2 on 2024-02-27 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime.now)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
